### ISSUE TITLE
Change defaultPhase to verify

### ISSUE THREAD

**Issue by balazs-zsoldos** [code-distillery/baselining-maven-plugin#11]
The default phase currently is "package". This phase is only responsible for creating the binary output (jar, war, etc.) but not check its quality.

The verify phase has the following definition: run any checks to verify the package is valid and meets quality criteria.

I think this is the phase where baselining plugin should run by default.

Another reason:

Some tools might want to execute (IDE plugins) the package phase skipping the test phase to deploy the binary output to a development server, where the developer can test the changes. Checking the version of the binary at this phase slows down this procedure.

**Comment by code-distillery** [comment]
Agreed, the verify phase sounds like a better default.

**Comment by code-distillery** [comment]
I've released the change in version 1.1.0. Thanks for the suggestion.
